import { readdirSync, readFileSync, writeFileSync, watch, mkdirSync } from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { evaluateSync } from "@mdx-js/mdx";
import { renderToStaticMarkup } from "react-dom/server";
import * as runtime from "react/jsx-runtime";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypeHighlight from "rehype-highlight";
import type { Root, Element } from "hast";
import type { Plugin } from "unified";
import { visit } from "unist-util-visit";
import type { Category, Lang, Post, TocItem } from "@/lib/posts";

const ROOT = path.resolve(import.meta.dir, "..");
const CONTENT_DIR = path.join(ROOT, "src", "content");
const OUT_FILE = path.join(ROOT, "src", "generated", "content.ts");

const CATEGORIES: Category[] = ["blog", "tech"];

const FILE_RE = /^(?<slug>.+)\.(?<lang>zh|en)\.mdx$/i;

const collectToc: Plugin<[{ toc: TocItem[] }], Root> = function (opts) {
  return (tree) => {
    visit(tree, "element", (node) => {
      if (node.tagName === "h1" || node.tagName === "h2" || node.tagName === "h3") {
        const id =
          typeof node.properties?.id === "string" ? node.properties.id : "";
        const text = elementText(node);
        if (id && text) {
          opts.toc.push({ id, text, level: Number(node.tagName[1]) });
        }
      }
    });
  };
};

function elementText(node: Element): string {
  return node.children
    .map((child) => {
      if (child.type === "text") return child.value;
      if (child.type === "element") return elementText(child);
      return "";
    })
    .join("");
}

interface RawFrontmatter {
  title?: unknown;
  date?: unknown;
  tags?: unknown;
  excerpt?: unknown;
}

function parseDate(value: unknown): string {
  const date = new Date(String(value ?? ""));
  if (Number.isNaN(date.getTime())) {
    throw new Error(`Invalid date: ${String(value)}`);
  }
  return date.toISOString().slice(0, 10);
}

function parseTags(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map((v) => String(v));
  }
  if (typeof value === "string") {
    return value
      .split(/[,，]/)
      .map((s) => s.trim())
      .filter(Boolean);
  }
  return [];
}

function readingTime(body: string): number {
  const text = body
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/[#>*_\-\[\]()!~|"']/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  const cjk = (text.match(/[\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af]/g) ?? [])
    .length;
  const words = text
    .replace(/[\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af]/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
  return Math.max(1, Math.round(cjk / 400 + words / 200));
}

function compileMdx(mdx: string, toc: TocItem[], file: string): string {
  const mod = evaluateSync(mdx, {
    development: false,
    jsx: runtime.jsx,
    jsxs: runtime.jsxs,
    Fragment: runtime.Fragment,
    rehypePlugins: [
      rehypeSlug,
      [collectToc, { toc }],
      [rehypeAutolinkHeadings, { behavior: "wrap" }],
      rehypeHighlight,
    ],
    remarkPlugins: [],
  });
  return renderToStaticMarkup(mod.default({}));
}

function build(watchMode: boolean): void {
  const posts: Post[] = [];

  for (const category of CATEGORIES) {
    const dir = path.join(CONTENT_DIR, category);
    if (!existsDir(dir)) continue;

    for (const file of readdirSync(dir)) {
      if (!/\.mdx$/i.test(file)) continue;
      const match = FILE_RE.exec(file);
      const groups = match?.groups;
      if (!groups) {
        console.warn(`  ⚠ skipped (unrecognized name): ${category}/${file}`);
        continue;
      }
      const filePath = path.join(dir, file);
      const source = readFileSync(filePath, "utf8");
      const { data, content: body } = matter(source);
      const fm = data as RawFrontmatter;

      const slug = groups.slug ?? "";
      const lang = (groups.lang ?? "zh").toLowerCase() as Lang;
      const title = String(fm.title ?? slug);
      const excerpt = String(fm.excerpt ?? "");

      const toc: TocItem[] = [];
      let html: string;
      try {
        html = compileMdx(body, toc, filePath);
      } catch (error) {
        console.error(`  ✗ failed to compile ${category}/${file}`);
        console.error(error);
        process.exitCode = 1;
        continue;
      }

      posts.push({
        key: `${category}/${slug}.${lang}`,
        category,
        lang,
        slug,
        title,
        date: parseDate(fm.date),
        tags: parseTags(fm.tags),
        excerpt,
        readingTime: readingTime(body),
        html,
        toc,
      });
    }
  }

  posts.sort((a, b) => (a.date === b.date ? 0 : a.date < b.date ? 1 : -1));

  const output = `/* eslint-disable */
// AUTO-GENERATED by scripts/build-content.ts — do not edit by hand.
// Run \`bun run build:content\` to regenerate after adding/changing posts.
import type { Post } from "@/lib/posts";

export const posts: Post[] = ${JSON.stringify(posts, null, 2)};
`;

  mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, output);
  console.log(`\n✓ content built: ${posts.length} posts → src/generated/content.ts`);

  for (const category of CATEGORIES) {
    const count = posts.filter((p) => p.category === category).length;
    if (count) console.log(`  ${category}: ${count}`);
  }

  if (watchMode) {
    console.log("  watching for changes…");
  }
}

function existsDir(p: string): boolean {
  try {
    return readdirSync(p).length >= 0;
  } catch {
    return false;
  }
}

build(process.argv.includes("--watch"));

if (process.argv.includes("--watch")) {
  watch(CONTENT_DIR, { recursive: true }, (event, filename) => {
    if (filename && /\.mdx$/i.test(filename)) {
      console.log(`\nchange: ${filename}`);
      build(true);
    }
  });
}