-- Supabase-native schema for the personal site.
--
-- The public client uses Supabase Auth and these RPC functions. No database
-- connection string or service-role key is ever sent to the browser.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  github_id bigint not null unique,
  login varchar(100) not null,
  avatar_url varchar(500) not null default '',
  name varchar(255),
  html_url varchar(500) not null default '',
  is_admin boolean not null default false,
  auth_user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users add column if not exists auth_user_id uuid;
do $$
begin
  alter table public.users
    add constraint users_auth_user_id_fkey
    foreign key (auth_user_id) references auth.users(id) on delete cascade;
exception
  when duplicate_object then null;
end
$$;
create unique index if not exists users_auth_user_id_key
  on public.users (auth_user_id)
  where auth_user_id is not null;

create table if not exists public.auth_sessions (
  token_hash varchar(64) primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);
create index if not exists ix_auth_sessions_expires_at
  on public.auth_sessions (expires_at);
create index if not exists ix_auth_sessions_user_id
  on public.auth_sessions (user_id);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  category varchar(32) not null,
  slug varchar(255) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_posts_category_slug unique (category, slug),
  constraint ck_posts_category check (category in ('blog', 'tech'))
);
create index if not exists ix_posts_category on public.posts (category);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete set null,
  source_node_id varchar(255) unique,
  body text not null,
  status varchar(20) not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_comments_status check (status in ('published', 'hidden')),
  constraint ck_comments_body_length check (char_length(body) between 1 and 5000)
);
alter table public.comments add column if not exists source_node_id varchar(255);
create unique index if not exists ix_comments_source_node_id
  on public.comments (source_node_id)
  where source_node_id is not null;
create index if not exists ix_comments_author_id on public.comments (author_id);
create index if not exists ix_comments_parent_id on public.comments (parent_id);
create index if not exists ix_comments_post_id on public.comments (post_id);

create table if not exists public.comment_reactions (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);
create index if not exists ix_comment_reactions_user_id
  on public.comment_reactions (user_id);

create table if not exists public.bookmarks (
  user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);
create index if not exists ix_bookmarks_post_id on public.bookmarks (post_id);

create table if not exists public.reading_progress (
  user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  progress_percent smallint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, post_id),
  constraint ck_reading_progress_range check (progress_percent between 0 and 100)
);
create index if not exists ix_reading_progress_post_id
  on public.reading_progress (post_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at
before update on public.users
for each row execute function public.touch_updated_at();

drop trigger if exists posts_touch_updated_at on public.posts;
create trigger posts_touch_updated_at
before update on public.posts
for each row execute function public.touch_updated_at();

drop trigger if exists comments_touch_updated_at on public.comments;
create trigger comments_touch_updated_at
before update on public.comments
for each row execute function public.touch_updated_at();

create or replace function public.current_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where auth_user_id = auth.uid() limit 1;
$$;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select is_admin from public.users where auth_user_id = auth.uid() limit 1),
    false
  );
$$;

create or replace function public.sync_auth_user(p_auth_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  auth_record auth.users%rowtype;
  existing_id bigint;
  provider_id bigint;
  user_login text;
  user_avatar_url text;
  user_name text;
  user_html_url text;
begin
  select * into auth_record from auth.users where id = p_auth_user_id;
  if not found then
    return null;
  end if;

  begin
    provider_id := nullif(auth_record.raw_user_meta_data ->> 'provider_id', '')::bigint;
  exception when invalid_text_representation then
    provider_id := null;
  end;

  user_login := left(coalesce(
    auth_record.raw_user_meta_data ->> 'user_name',
    auth_record.raw_user_meta_data ->> 'preferred_username',
    auth_record.raw_user_meta_data ->> 'name',
    split_part(coalesce(auth_record.email, p_auth_user_id::text), '@', 1),
    p_auth_user_id::text
  ), 100);
  user_avatar_url := left(coalesce(auth_record.raw_user_meta_data ->> 'avatar_url', ''), 500);
  user_name := left(coalesce(
    auth_record.raw_user_meta_data ->> 'full_name',
    auth_record.raw_user_meta_data ->> 'name',
    user_login
  ), 255);
  user_html_url := left(coalesce(
    auth_record.raw_user_meta_data ->> 'html_url',
    'https://github.com/' || user_login
  ), 500);

  select id into existing_id
  from public.users
  where auth_user_id = p_auth_user_id
     or (provider_id is not null and github_id = provider_id)
  order by (auth_user_id = p_auth_user_id) desc
  limit 1;

  if existing_id is null then
    if provider_id is null then
      provider_id := abs(hashtextextended(p_auth_user_id::text, 0));
    end if;
    insert into public.users (
      github_id,
      login,
      avatar_url,
      name,
      html_url,
      auth_user_id
    ) values (
      provider_id,
      user_login,
      user_avatar_url,
      user_name,
      user_html_url,
      p_auth_user_id
    ) returning id into existing_id;
  else
    update public.users
    set auth_user_id = p_auth_user_id,
        github_id = coalesce(provider_id, github_id),
        login = user_login,
        avatar_url = user_avatar_url,
        name = user_name,
        html_url = user_html_url
    where id = existing_id;
  end if;

  return existing_id;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.sync_auth_user(new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of raw_user_meta_data on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.ensure_profile()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  return public.sync_auth_user(auth.uid());
end;
$$;

create or replace function public.ensure_post(p_category text, p_slug text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  post_id bigint;
begin
  if p_category not in ('blog', 'tech')
     or p_slug is null
     or p_slug !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$' then
    raise exception 'invalid_target' using errcode = '22023';
  end if;

  insert into public.posts (category, slug)
  values (p_category, p_slug)
  on conflict (category, slug) do update set updated_at = now()
  returning id into post_id;
  return post_id;
end;
$$;

create or replace function public.get_comments(p_category text, p_slug text)
returns table (
  id bigint,
  body text,
  created_at timestamptz,
  updated_at timestamptz,
  parent_id bigint,
  author_id text,
  author_login text,
  author_avatar_url text,
  author_name text,
  author_html_url text,
  thumbs_up bigint,
  viewer_has_reacted boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.body,
    c.created_at,
    c.updated_at,
    c.parent_id,
    u.id::text,
    u.login::text,
    u.avatar_url::text,
    u.name::text,
    u.html_url::text,
    count(r.user_id)::bigint,
    coalesce(bool_or(r.user_id = public.current_user_id()), false)
  from public.comments c
  join public.posts p on p.id = c.post_id
  join public.users u on u.id = c.author_id
  left join public.comment_reactions r on r.comment_id = c.id
  where p.category = p_category
    and p.slug = p_slug
    and (c.status = 'published' or public.current_user_is_admin())
  group by c.id, c.body, c.created_at, c.updated_at, c.parent_id,
    u.id, u.login, u.avatar_url, u.name, u.html_url
  order by c.created_at asc, c.id asc;
$$;

create or replace function public.add_comment(
  p_category text,
  p_slug text,
  p_body text,
  p_parent_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post_id bigint;
  author_id bigint;
  comment_id bigint;
  normalized_body text;
begin
  author_id := public.current_user_id();
  if author_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  normalized_body := btrim(coalesce(p_body, ''));
  if char_length(normalized_body) not between 1 and 5000 then
    raise exception 'invalid_comment_body' using errcode = '22023';
  end if;

  v_post_id := public.ensure_post(p_category, p_slug);
  if p_parent_id is not null and not exists (
    select 1 from public.comments c
    where c.id = p_parent_id and c.post_id = v_post_id and c.status = 'published'
  ) then
    raise exception 'invalid_parent' using errcode = '22023';
  end if;

  insert into public.comments (post_id, author_id, parent_id, body)
  values (v_post_id, author_id, p_parent_id, normalized_body)
  returning id into comment_id;
  return comment_id;
end;
$$;

create or replace function public.set_comment_reaction(p_comment_id bigint, p_liked boolean)
returns table (comment_id bigint, liked boolean, thumbs_up bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  viewer_id bigint;
begin
  viewer_id := public.current_user_id();
  if viewer_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if not exists (
    select 1 from public.comments where id = p_comment_id and status = 'published'
  ) then
    raise exception 'comment_not_found' using errcode = 'P0002';
  end if;

  if p_liked then
    insert into public.comment_reactions (comment_id, user_id)
    values (p_comment_id, viewer_id)
    on conflict (comment_id, user_id) do nothing;
  else
    delete from public.comment_reactions
    where comment_id = p_comment_id and user_id = viewer_id;
  end if;

  return query
  select p_comment_id, p_liked, count(*)::bigint
  from public.comment_reactions
  where comment_id = p_comment_id;
end;
$$;

create or replace function public.get_bookmarks()
returns table (category text, slug text, bookmarked boolean, created_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select p.category::text, p.slug::text, true, b.created_at
  from public.bookmarks b
  join public.posts p on p.id = b.post_id
  where b.user_id = public.current_user_id()
  order by b.created_at desc;
$$;

create or replace function public.set_bookmark(
  p_category text,
  p_slug text,
  p_bookmarked boolean
)
returns table (category text, slug text, bookmarked boolean, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  viewer_id bigint;
  v_post_id bigint;
  bookmark_created_at timestamptz;
begin
  viewer_id := public.current_user_id();
  if viewer_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  v_post_id := public.ensure_post(p_category, p_slug);

  if p_bookmarked then
    insert into public.bookmarks (user_id, post_id)
    values (viewer_id, v_post_id)
    on conflict (user_id, post_id) do nothing;
    select b.created_at into bookmark_created_at
    from public.bookmarks b
    where b.user_id = viewer_id and b.post_id = v_post_id;
  else
    delete from public.bookmarks where user_id = viewer_id and post_id = v_post_id;
  end if;

  return query select p_category, p_slug, p_bookmarked, bookmark_created_at;
end;
$$;

create or replace function public.get_progress(p_category text, p_slug text)
returns table (category text, slug text, progress integer, updated_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select p.category::text, p.slug::text,
    coalesce(r.progress_percent, 0)::integer, r.updated_at
  from public.posts p
  left join public.reading_progress r
    on r.post_id = p.id and r.user_id = public.current_user_id()
  where p.category = p_category and p.slug = p_slug;
$$;

create or replace function public.set_progress(
  p_category text,
  p_slug text,
  p_progress integer
)
returns table (category text, slug text, progress integer, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  viewer_id bigint;
  v_post_id bigint;
  saved_at timestamptz;
begin
  viewer_id := public.current_user_id();
  if viewer_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_progress not between 0 and 100 then
    raise exception 'invalid_progress' using errcode = '22023';
  end if;
  v_post_id := public.ensure_post(p_category, p_slug);

  insert into public.reading_progress (user_id, post_id, progress_percent, updated_at)
  values (viewer_id, v_post_id, p_progress, now())
  on conflict (user_id, post_id) do update
    set progress_percent = excluded.progress_percent,
        updated_at = now()
  returning reading_progress.updated_at into saved_at;

  return query select p_category, p_slug, p_progress, saved_at;
end;
$$;

create or replace function public.moderate_comment(p_comment_id bigint, p_status text)
returns table (id bigint, status text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;
  if p_status not in ('published', 'hidden') then
    raise exception 'invalid_status' using errcode = '22023';
  end if;

  return query
  update public.comments
  set status = p_status
  where public.comments.id = p_comment_id
  returning public.comments.id, public.comments.status;
end;
$$;

alter table public.users enable row level security;
alter table public.auth_sessions enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.comment_reactions enable row level security;
alter table public.bookmarks enable row level security;
alter table public.reading_progress enable row level security;

drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users
for select to authenticated
using (auth_user_id = auth.uid() or public.current_user_is_admin());

revoke all on public.users, public.auth_sessions, public.posts, public.comments,
  public.comment_reactions, public.bookmarks, public.reading_progress
from anon, authenticated;
grant select on public.users to authenticated;

revoke all on function public.sync_auth_user(uuid) from public, anon, authenticated;
revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
revoke all on function public.ensure_post(text, text) from public, anon, authenticated;
revoke all on function public.ensure_profile() from public, anon, authenticated;
revoke all on function public.add_comment(text, text, text, bigint) from public, anon, authenticated;
revoke all on function public.set_comment_reaction(bigint, boolean) from public, anon, authenticated;
revoke all on function public.get_bookmarks() from public, anon, authenticated;
revoke all on function public.set_bookmark(text, text, boolean) from public, anon, authenticated;
revoke all on function public.get_progress(text, text) from public, anon, authenticated;
revoke all on function public.set_progress(text, text, integer) from public, anon, authenticated;
revoke all on function public.moderate_comment(bigint, text) from public, anon, authenticated;

grant execute on function public.ensure_profile() to authenticated;
grant execute on function public.get_comments(text, text) to anon, authenticated;
grant execute on function public.add_comment(text, text, text, bigint) to authenticated;
grant execute on function public.set_comment_reaction(bigint, boolean) to authenticated;
grant execute on function public.get_bookmarks() to authenticated;
grant execute on function public.set_bookmark(text, text, boolean) to authenticated;
grant execute on function public.get_progress(text, text) to authenticated;
grant execute on function public.set_progress(text, text, integer) to authenticated;
grant execute on function public.moderate_comment(bigint, text) to authenticated;
