-- Move the existing MDX articles into Supabase Postgres.
--
-- public.posts remains the stable article identity used by comments,
-- bookmarks and reading progress. Localized content lives in
-- public.post_translations so the two language versions share one post id.

alter table public.posts
  add column if not exists published_on date,
  add column if not exists is_published boolean not null default true;

create index if not exists ix_posts_published
  on public.posts (is_published, published_on desc, id desc);

create table if not exists public.post_translations (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  lang varchar(2) not null,
  title text not null,
  excerpt text not null default '',
  tags text[] not null default '{}'::text[],
  reading_time smallint not null default 1,
  source_mdx text not null default '',
  body_html text not null,
  toc jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_post_translations_post_lang unique (post_id, lang),
  constraint ck_post_translations_lang check (lang in ('zh', 'en')),
  constraint ck_post_translations_reading_time check (reading_time between 1 and 10000),
  constraint ck_post_translations_toc check (jsonb_typeof(toc) = 'array')
);

create index if not exists ix_post_translations_post_id
  on public.post_translations (post_id);
create index if not exists ix_post_translations_lang
  on public.post_translations (lang);

drop trigger if exists post_translations_touch_updated_at on public.post_translations;
create trigger post_translations_touch_updated_at
before update on public.post_translations
for each row execute function public.touch_updated_at();

insert into public.posts (category, slug, published_on, is_published)
values ($category$tech$category$, $slug$bun-react-setup$slug$, $date$2026-08-28$date$::date, true)
on conflict (category, slug) do update set
  published_on = excluded.published_on,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.post_translations (
  post_id, lang, title, excerpt, tags, reading_time, source_mdx, body_html, toc
)
select
  p.id,
  $lang$en$lang$,
  $title$Building this site with Bun + React$title$,
  $excerpt$How I built this site with Bun, React 19, and shadcn/ui, including the MDX content pipeline.$excerpt$,
  ARRAY[$tag$Bun$tag$, $tag$React$tag$, $tag$Tailwind$tag$]::text[],
  1,
  $mdx$---
title: "Building this site with Bun + React"
date: "2026-08-28"
tags: ["Bun", "React", "Tailwind"]
excerpt: "How I built this site with Bun, React 19, and shadcn/ui, including the MDX content pipeline."
---

## Why This Stack

The bar for choosing tools is simple: **the least moving parts, the fastest feedback**.

- **Bun** acts as both runtime and bundler; one command to run, zero config.
- **React 19 + shadcn/ui** keeps me from writing buttons and cards from scratch.
- **Tailwind CSS v4** defines the theme with CSS variables; dark mode is almost free.

## The Content Pipeline

The site is fully static (deployed to GitHub Pages), and every post is an **MDX file**:

```
src/content/<category>/<slug>.<lang>.mdx
```

The build script `scripts/build-content.ts` processes each post:

1. Parse frontmatter with `gray-matter` (title, date, tags, excerpt).
2. Compile Markdown + JSX to React elements with `@mdx-js/mdx`'s `evaluateSync`.
3. Render to a static HTML string with `react-dom/server`'s `renderToStaticMarkup`.
4. Generate anchor ids with `rehype-slug` and collect headings into a TOC.
5. Apply syntax highlighting with `rehype-highlight`.
6. Write everything into `src/generated/content.ts` for the frontend to import.

## Syntax Highlighting

```ts
function computeReadingTime(text: string): number {
  const words = text.replace(/\s+/g, " ").trim().split(" ").length;
  return Math.max(1, Math.round(words / 200));
}
```

## Gotchas Hit Along the Way

- `@types/gray-matter` does not exist on npm; gray-matter ships its own types.
- Running the shadcn CLI via `npx` crashes on a missing `@ts-morph/common`; using the local `bun x shadcn` works.
- The Tooltip component from shadcn requires a wrapping `TooltipProvider`.

## Summary

The payoff: **content written in Markdown, UI drawn in React, single-pass build, fully static output.**$mdx$,
  $html$<h2 id="why-this-stack"><a href="#why-this-stack">Why This Stack</a></h2>
<p>The bar for choosing tools is simple: <strong>the least moving parts, the fastest feedback</strong>.</p>
<ul>
<li><strong>Bun</strong> acts as both runtime and bundler; one command to run, zero config.</li>
<li><strong>React 19 + shadcn/ui</strong> keeps me from writing buttons and cards from scratch.</li>
<li><strong>Tailwind CSS v4</strong> defines the theme with CSS variables; dark mode is almost free.</li>
</ul>
<h2 id="the-content-pipeline"><a href="#the-content-pipeline">The Content Pipeline</a></h2>
<p>The site is fully static (deployed to GitHub Pages), and every post is an <strong>MDX file</strong>:</p>
<pre><code>src/content/&lt;category&gt;/&lt;slug&gt;.&lt;lang&gt;.mdx
</code></pre>
<p>The build script <code>scripts/build-content.ts</code> processes each post:</p>
<ol>
<li>Parse frontmatter with <code>gray-matter</code> (title, date, tags, excerpt).</li>
<li>Compile Markdown + JSX to React elements with <code>@mdx-js/mdx</code>&#x27;s <code>evaluateSync</code>.</li>
<li>Render to a static HTML string with <code>react-dom/server</code>&#x27;s <code>renderToStaticMarkup</code>.</li>
<li>Generate anchor ids with <code>rehype-slug</code> and collect headings into a TOC.</li>
<li>Apply syntax highlighting with <code>rehype-highlight</code>.</li>
<li>Write everything into <code>src/generated/content.ts</code> for the frontend to import.</li>
</ol>
<h2 id="syntax-highlighting"><a href="#syntax-highlighting">Syntax Highlighting</a></h2>
<pre><code class="hljs language-ts"><span class="hljs-keyword">function</span> <span class="hljs-title function_">computeReadingTime</span>(<span class="hljs-params"><span class="hljs-attr">text</span>: <span class="hljs-built_in">string</span></span>): <span class="hljs-built_in">number</span> {
  <span class="hljs-keyword">const</span> words = text.<span class="hljs-title function_">replace</span>(<span class="hljs-regexp">/\s+/g</span>, <span class="hljs-string">&quot; &quot;</span>).<span class="hljs-title function_">trim</span>().<span class="hljs-title function_">split</span>(<span class="hljs-string">&quot; &quot;</span>).<span class="hljs-property">length</span>;
  <span class="hljs-keyword">return</span> <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">max</span>(<span class="hljs-number">1</span>, <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">round</span>(words / <span class="hljs-number">200</span>));
}
</code></pre>
<h2 id="gotchas-hit-along-the-way"><a href="#gotchas-hit-along-the-way">Gotchas Hit Along the Way</a></h2>
<ul>
<li><code>@types/gray-matter</code> does not exist on npm; gray-matter ships its own types.</li>
<li>Running the shadcn CLI via <code>npx</code> crashes on a missing <code>@ts-morph/common</code>; using the local <code>bun x shadcn</code> works.</li>
<li>The Tooltip component from shadcn requires a wrapping <code>TooltipProvider</code>.</li>
</ul>
<h2 id="summary"><a href="#summary">Summary</a></h2>
<p>The payoff: <strong>content written in Markdown, UI drawn in React, single-pass build, fully static output.</strong></p>$html$,
  $toc$[{"id":"why-this-stack","text":"Why This Stack","level":2},{"id":"the-content-pipeline","text":"The Content Pipeline","level":2},{"id":"syntax-highlighting","text":"Syntax Highlighting","level":2},{"id":"gotchas-hit-along-the-way","text":"Gotchas Hit Along the Way","level":2},{"id":"summary","text":"Summary","level":2}]$toc$::jsonb
from public.posts p
where p.category = $category_lookup$tech$category_lookup$
  and p.slug = $slug_lookup$bun-react-setup$slug_lookup$
on conflict (post_id, lang) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  tags = excluded.tags,
  reading_time = excluded.reading_time,
  source_mdx = excluded.source_mdx,
  body_html = excluded.body_html,
  toc = excluded.toc,
  updated_at = now();

insert into public.posts (category, slug, published_on, is_published)
values ($category$tech$category$, $slug$bun-react-setup$slug$, $date$2026-08-28$date$::date, true)
on conflict (category, slug) do update set
  published_on = excluded.published_on,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.post_translations (
  post_id, lang, title, excerpt, tags, reading_time, source_mdx, body_html, toc
)
select
  p.id,
  $lang$zh$lang$,
  $title$用 Bun + React 搭建个人网站$title$,
  $excerpt$记录用 Bun、React 19 和 shadcn/ui 搭建这个网站的过程，包括 MDX 内容流水线的设计。$excerpt$,
  ARRAY[$tag$Bun$tag$, $tag$React$tag$, $tag$Tailwind$tag$]::text[],
  1,
  $mdx$---
title: "用 Bun + React 搭建个人网站"
date: "2026-08-28"
tags: ["Bun", "React", "Tailwind"]
excerpt: "记录用 Bun、React 19 和 shadcn/ui 搭建这个网站的过程，包括 MDX 内容流水线的设计。"
---

## 为什么选这个技术栈

选工具的标准很简单：**尽量少的东西，尽量快的反馈**。

- **Bun** 同时扮演了运行时和打包器的角色，一条命令跑起来，零配置。
- **React 19 + shadcn/ui** 让我不用从零写按钮和卡片，把精力留给内容本身。
- **Tailwind CSS v4** 用 CSS 变量定义主题，暗色模式几乎是免费的。

## 内容流水线的设计

网站是纯静态部署（GitHub Pages），所有文章是 **MDX 文件**：

```
src/content/<category>/<slug>.<lang>.mdx
```

构建脚本 `scripts/build-content.ts` 逐篇处理：

1. 用 `gray-matter` 解析 frontmatter（标题、日期、标签、摘要）。
2. 用 `@mdx-js/mdx` 的 `evaluateSync` 把 Markdown + JSX 编译成 React 元素。
3. 用 `react-dom/server` 的 `renderToStaticMarkup` 输出静态 HTML 字符串。
4. 用 `rehype-slug` 给标题生成锚点 id，再收集成目录（TOC）。
5. 用 `rehype-highlight` 做代码语法高亮。
6. 最后把所有文章写进 `src/generated/content.ts`，前端直接 import。

这样内容既能被 React 渲染，又被预编译成纯 HTML，SEO 和加载速度都有保障。

## 代码高亮

```ts
function computeReadingTime(text: string): number {
  const words = text.replace(/\s+/g, " ").trim().split(" ").length;
  return Math.max(1, Math.round(words / 200));
}
```

## 踩过的几个坑

- `@types/gray-matter` 在 npm 上不存在，gray-matter 自带类型。
- npx 跑 shadcn CLI 会因缺 `@ts-morph/common` 崩溃，改用本地 `bun x shadcn` 就好了。
- shadcn 的 Tooltip 组件需要在外层包一个 `TooltipProvider`。

## 小结

这套方案的好处是：**内容用 Markdown 写，界面用 React 画，构建一次搞定，部署全是静态文件。**
改一篇文章，跑一次 `bun run build:content`，再部署，完事。$mdx$,
  $html$<h2 id="为什么选这个技术栈"><a href="#为什么选这个技术栈">为什么选这个技术栈</a></h2>
<p>选工具的标准很简单：<strong>尽量少的东西，尽量快的反馈</strong>。</p>
<ul>
<li><strong>Bun</strong> 同时扮演了运行时和打包器的角色，一条命令跑起来，零配置。</li>
<li><strong>React 19 + shadcn/ui</strong> 让我不用从零写按钮和卡片，把精力留给内容本身。</li>
<li><strong>Tailwind CSS v4</strong> 用 CSS 变量定义主题，暗色模式几乎是免费的。</li>
</ul>
<h2 id="内容流水线的设计"><a href="#内容流水线的设计">内容流水线的设计</a></h2>
<p>网站是纯静态部署（GitHub Pages），所有文章是 <strong>MDX 文件</strong>：</p>
<pre><code>src/content/&lt;category&gt;/&lt;slug&gt;.&lt;lang&gt;.mdx
</code></pre>
<p>构建脚本 <code>scripts/build-content.ts</code> 逐篇处理：</p>
<ol>
<li>用 <code>gray-matter</code> 解析 frontmatter（标题、日期、标签、摘要）。</li>
<li>用 <code>@mdx-js/mdx</code> 的 <code>evaluateSync</code> 把 Markdown + JSX 编译成 React 元素。</li>
<li>用 <code>react-dom/server</code> 的 <code>renderToStaticMarkup</code> 输出静态 HTML 字符串。</li>
<li>用 <code>rehype-slug</code> 给标题生成锚点 id，再收集成目录（TOC）。</li>
<li>用 <code>rehype-highlight</code> 做代码语法高亮。</li>
<li>最后把所有文章写进 <code>src/generated/content.ts</code>，前端直接 import。</li>
</ol>
<p>这样内容既能被 React 渲染，又被预编译成纯 HTML，SEO 和加载速度都有保障。</p>
<h2 id="代码高亮"><a href="#代码高亮">代码高亮</a></h2>
<pre><code class="hljs language-ts"><span class="hljs-keyword">function</span> <span class="hljs-title function_">computeReadingTime</span>(<span class="hljs-params"><span class="hljs-attr">text</span>: <span class="hljs-built_in">string</span></span>): <span class="hljs-built_in">number</span> {
  <span class="hljs-keyword">const</span> words = text.<span class="hljs-title function_">replace</span>(<span class="hljs-regexp">/\s+/g</span>, <span class="hljs-string">&quot; &quot;</span>).<span class="hljs-title function_">trim</span>().<span class="hljs-title function_">split</span>(<span class="hljs-string">&quot; &quot;</span>).<span class="hljs-property">length</span>;
  <span class="hljs-keyword">return</span> <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">max</span>(<span class="hljs-number">1</span>, <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">round</span>(words / <span class="hljs-number">200</span>));
}
</code></pre>
<h2 id="踩过的几个坑"><a href="#踩过的几个坑">踩过的几个坑</a></h2>
<ul>
<li><code>@types/gray-matter</code> 在 npm 上不存在，gray-matter 自带类型。</li>
<li>npx 跑 shadcn CLI 会因缺 <code>@ts-morph/common</code> 崩溃，改用本地 <code>bun x shadcn</code> 就好了。</li>
<li>shadcn 的 Tooltip 组件需要在外层包一个 <code>TooltipProvider</code>。</li>
</ul>
<h2 id="小结"><a href="#小结">小结</a></h2>
<p>这套方案的好处是：<strong>内容用 Markdown 写，界面用 React 画，构建一次搞定，部署全是静态文件。</strong>
改一篇文章，跑一次 <code>bun run build:content</code>，再部署，完事。</p>$html$,
  $toc$[{"id":"为什么选这个技术栈","text":"为什么选这个技术栈","level":2},{"id":"内容流水线的设计","text":"内容流水线的设计","level":2},{"id":"代码高亮","text":"代码高亮","level":2},{"id":"踩过的几个坑","text":"踩过的几个坑","level":2},{"id":"小结","text":"小结","level":2}]$toc$::jsonb
from public.posts p
where p.category = $category_lookup$tech$category_lookup$
  and p.slug = $slug_lookup$bun-react-setup$slug_lookup$
on conflict (post_id, lang) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  tags = excluded.tags,
  reading_time = excluded.reading_time,
  source_mdx = excluded.source_mdx,
  body_html = excluded.body_html,
  toc = excluded.toc,
  updated_at = now();

create or replace function public.upsert_post_translation(
  p_category text,
  p_slug text,
  p_published_on date,
  p_is_published boolean,
  p_lang text,
  p_title text,
  p_excerpt text,
  p_tags text[],
  p_reading_time smallint,
  p_source_mdx text,
  p_body_html text,
  p_toc jsonb
)
returns public.post_translations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post_id bigint;
  v_translation public.post_translations;
begin
  if not public.current_user_is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if p_category not in ('blog', 'tech')
     or p_slug is null
     or p_slug !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$'
     or p_lang not in ('zh', 'en')
     or nullif(btrim(coalesce(p_title, '')), '') is null
     or nullif(btrim(coalesce(p_body_html, '')), '') is null
     or p_reading_time not between 1 and 10000
     or jsonb_typeof(coalesce(p_toc, '[]'::jsonb)) <> 'array' then
    raise exception 'invalid_post' using errcode = '22023';
  end if;

  insert into public.posts (category, slug, published_on, is_published)
  values (p_category, p_slug, p_published_on, coalesce(p_is_published, true))
  on conflict (category, slug) do update set
    published_on = excluded.published_on,
    is_published = excluded.is_published,
    updated_at = now()
  returning id into v_post_id;

  insert into public.post_translations (
    post_id,
    lang,
    title,
    excerpt,
    tags,
    reading_time,
    source_mdx,
    body_html,
    toc
  )
  values (
    v_post_id,
    p_lang,
    btrim(p_title),
    coalesce(p_excerpt, ''),
    coalesce(p_tags, '{}'::text[]),
    p_reading_time,
    coalesce(p_source_mdx, ''),
    p_body_html,
    coalesce(p_toc, '[]'::jsonb)
  )
  on conflict (post_id, lang) do update set
    title = excluded.title,
    excerpt = excluded.excerpt,
    tags = excluded.tags,
    reading_time = excluded.reading_time,
    source_mdx = excluded.source_mdx,
    body_html = excluded.body_html,
    toc = excluded.toc,
    updated_at = now()
  returning * into v_translation;

  return v_translation;
end;
$$;

revoke all on public.post_translations from anon, authenticated;
grant select on public.posts, public.post_translations to anon, authenticated;

revoke all on function public.upsert_post_translation(
  text, text, date, boolean, text, text, text, text[], smallint, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.upsert_post_translation(
  text, text, date, boolean, text, text, text, text[], smallint, text, text, jsonb
) to authenticated;

alter table public.posts enable row level security;
alter table public.post_translations enable row level security;

drop policy if exists posts_select_published on public.posts;
create policy posts_select_published on public.posts
for select to anon, authenticated
using (is_published = true or public.current_user_is_admin());

drop policy if exists post_translations_select_published on public.post_translations;
create policy post_translations_select_published on public.post_translations
for select to anon, authenticated
using (
  exists (
    select 1
    from public.posts p
    where p.id = post_id
      and (p.is_published = true or public.current_user_is_admin())
  )
);

